name: Daily Backup

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' 

env:
    target: https://github.com/canonical/chisel-releases.git
    # output: %y%m%d-chisel-releases.git.tar.gz
    artifact-name: chisel-releases.git.tar.gz

jobs:
  backup:
    runs-on: ubuntu-24.04
    steps:

      - name: Backup
        id: backup
        run: |
          git clone --mirror ${{ env.target }} 
          tar -czf backup.tar.gz *.git

          # name=$(date "")
          # echo "backup_name=${name}" >> $GITHUB_OUTPUT

      - name: Upload
        uses: actions/upload-artifact@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ env.artifact-name }}
          path: "*.git"
          retention-days: 90
          compression-level: 9
          overwrite: false


