name: Daily Backup

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' 

env:
    target: https://github.com/canonical/chisel-releases.git
    artifact-name: chisel-releases_%y%m%d.git.tar.gz
    asset-name-template: chisel-releases.git.tar.gz
    upload_url: https://github.com/clay-lake/chisel-releases-snapshots/releases/tag/archive

jobs:
  backup:
    runs-on: ubuntu-24.04
    steps:

      - name: Backup
        id: backup
        run: |
          git clone --mirror ${{ env.target }} 
          tar -czf backup.tar.gz *.git

          echo ${{ github.event.schedule }}

          name=$(date +"${{ env.asset-name-template }}")
          echo "asset_name=${name}" >> $GITHUB_OUTPUT

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ env.artifact-name }}
          path: "*.git"
          retention-days: 90
          compression-level: 9
          overwrite: false

      - name: Upload Asset
        # if: startsWith(github.event.schedule, '0 2 15') # Executes only on the first of each month
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.upload_url }}
          asset_path: backup.tar.gz
          asset_name: ${{ steps.backup.outputs.asset_name }}
          asset_content_type: application/gzip


